apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kong-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kong-db
  template:
    metadata:
      labels:
        app: kong-db
    spec:
      containers:
      - name: kong-db
        image: postgres:latest
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: kong
        - name: POSTGRES_USER
          value: kong
        - name: POSTGRES_PASSWORD
          value: kong
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: kong-db-storage
        readinessProbe:
          exec:
            command: ["pg_isready", "-U", "kong"]
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5
      volumes:
      - name: kong-db-storage
        persistentVolumeClaim:
          claimName: kong-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: kong-db
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: kong-db
