apiVersion: batch/v1
kind: Job
metadata:
  name: kong-migrations
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: kong-migrations
        image: kong/kong-gateway:latest
        command: ["kong", "migrations", "bootstrap"]
        env:
        - name: KONG_DATABASE
          value: postgres
        - name: KONG_PG_HOST
          value: kong-db
        - name: KONG_PG_DATABASE
          value: kong
        - name: KONG_PG_USER
          value: kong
        - name: KONG_PG_PASSWORD
          value: kong
